### ISSUE TITLE
server-down2.test

### ISSUE THREAD

**Issue by afd998** [zachjicha/cse130-tests#2] opened 2020-06-01 04:34 UTC
it expects a 200 but its testing if we can tell if a server is down and i think it should be expecting a 500

**Comment by zachjicha** [comment] 2020-06-01 06:44
server-down2.test runs 2 httpservers, one with 50 requests and the other with 0. The one with 0 is killed after the first health check. The test is designed to see if your loadbalancer still can direct the client to a server that is thought to be operational. 

Admittedly, the structure of the test is not the greatest, but I do not see another way of testing for partial failure of servers.

A 500 should only be received if all servers are down, or if the server the client is directed to times out. I am trying to develope a test for the latter scenarior, and the former is covered by all of the other server-down test cases.

I hope this clarifies the test. If you have any other comments or suggestions, feel free to leave them here, otherwise I will close this issue in a day or so.

**Comment by zachjicha** [comment] 2020-06-01 06:49
Also, the server-down tests were unreliable, and I believe I fixed this unreliability in the most recent commit, please make sure you have this fix

**Comment by afd998** [comment] 2020-06-01 19:49
Isn't the test killing the "good server?" KILLPID=$! kills the last background task which is the server with no requests in its log.

**Comment by zachjicha** [comment] 2020-06-01 21:27
Yes. The idea is that the loadbalancer will be biased to send the request to this server, but it is down. So it needs to be able to figure this out and send it to the next best available server, which is the one with 50 requests.

**Comment by afd998** [comment] 2020-06-01 21:36
I see. I guess the thing is that the initial health check says everything is all good. Then we kill the good server, but we only wait 0.25 seconds so that isn't enough time (depending on your X) for a second health check to happens and tell us that the good server is now down. The second sleep needs to be larger than the users X value. Then it works.

**Comment by zachjicha** [comment] 2020-06-01 21:41
Ah I see what you are saying. I may have misundertsood the spec/piazza. 

It was my undertsanding that if you connect to a server you think is up but the connect call fails, you should keep trying to redirect to another server that is up until you confirm all servers are down. 

However, reading the post I got this from, this may be incorrect. I will do some more reading later today and see what the intended behavior is after my classes. Thank you for pointing this out!

**Comment by zachjicha** [comment] 2020-06-01 21:58
I believe it is also likely other tests in this class may have a similar issue.

**Comment by zachjicha** [comment] 2020-06-01 23:45
I believe I have fixed the issue, let me know if there are still issues. Thanks for your input!

**Closed** 2020-06-02 20:55 UTC
Labels: incorrect behavior
